# Compose file is designed to run this on a local machine for development.
version: "3"
services:
  wordpress-starter-react-theme:
    container_name: wordpress-starter-react-theme
    image: maddog986/php-nginx-mysql-server:latest
    volumes:
      - ./wordpress_theme:/home/site/wwwroot/wwwroot/wp-content/themes/wordpress_theme
    ports:
      - 8085:80 # web port
      # - 3306:3306 # mysql
      # - 2222:2222 #used for Azure Web App Containers
    environment:
      - PHPMYADMIN_VERSION=5.1.0
      - WEBSITE_HOSTNAME=localhost:3000 # wordpress goes through webpack dev server
      - WORDPRESS_INSTALL=true
      - WORDPRESS_TITLE=WordPress
      - WORDPRESS_ADMIN_EMAIL=noemail@domain.com
      - WORDPRESS_ACTIVATE_THEME=wordpress_theme
      - WORDPRESS_ADMIN_USERNAME=admin
      - WORDPRESS_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      wsp_network:
        ipv4_address: 172.35.30.99

networks:
  wsp_network:
    ipam:
      driver: default
      config:
        - subnet: 172.35.30.0/16
