# Compose file is designed to run this on a local machine for development.
version: "3"
services:
  wordpress-starter-react-theme:
    container_name: wordpress-starter-react-theme
    image: maddog986/php-nginx-mysql-server:latest
    volumes:
      - ./wordpress_theme:/var/www/wp-content/themes/wordpress_theme/
    ports:
      - 8085:80 # web port
    environment:
      - WEBSITE_HOSTNAME=localhost:3000 # wordpress goes through webpack dev server
      - WORDPRESS_VERSION=latest
      - WORDPRESS_TITLE=WordPress
      - WORDPRESS_ACTIVATE_THEME=wordpress_theme
      - WORDPRESS_ADMIN_USERNAME=admin
      - WORDPRESS_ADMIN_PASSWORD=admin
      - WORDPRESS_ADMIN_EMAIL=noemail@domain.com
    restart: unless-stopped
    networks:
      wsp_network:
        ipv4_address: 172.35.30.99

networks:
  wsp_network:
    ipam:
      driver: default
      config:
        - subnet: 172.35.30.0/16
